# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ravindra_Sandun-COBSCCOMP192P-054' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ravindra_Sandun-COBSCCOMP192P-054

    pod 'Firebase/Analytics'

    pod 'Firebase/Auth'

    pod 'Firebase/Database'

    pod 'Firebase/Core'

    pod 'Firebase/Firestore'

    pod 'Firebase/Storage'

end
